# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "5.4"

image:
  repository: "centerforopenscience/elasticsearch"
  tag: "5.4"
  pullPolicy: "IfNotPresent"

cluster:
  name: "elasticsearch"
  config:
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "2"
  plugins:
    list:
      ## if you wish to use your own list of plugins
      ## remember to include the 'cloud-kubernetes' plugin listed below
      ## otherwise you'll be getting 'Unknown Discovery type [kubernetes]' errors! 
      # cloud-kubernetes:
      #   url: "io.fabric8:elasticsearch-cloud-kubernetes:5.4.2"
      # analysis-icu:
      ## For officially supported plugins you can leave the 'url' field empty
      #   url:
    volume:
      name: plugins
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 256Mi
  customScripts:
    ## Chart does NOT create the configMap for you!
    ## You'll have to create one on your own.
    #configMap: my-es-scripts

client:
  name: client
  replicas: 2
  serviceType: ClusterIP

## (dict) If specified, apply these annotations to the client service
#  serviceAnnotations:
#    example: client-svc-foo

  heapSize: "512m"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      # memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"
  ## (dict) If specified, apply these annotations to each client Pod
  # podAnnotations:
  #   example: client-foo

master:
  name: master
  exposeHttp: false
  replicas: 3
  heapSize: "512m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "4Gi"
    # storageClass: "ssd"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      # memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"

  ## (dict) If specified, apply these annotations to each master Pod
  # podAnnotations:
  #   example: master-foo

data:
  name: data
  exposeHttp: false
  replicas: 2
  heapSize: "1536m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "30Gi"
    # storageClass: "ssd"
  terminationGracePeriodSeconds: 3600
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      # memory: "2048Mi"
    requests:
      cpu: "25m"
      memory: "1536Mi"


  ## (dict) If specified, apply these annotations to each data Pod
  # podAnnotations:
  #   example: data-foo

## Install Default RBAC roles and bindings
rbac:
  create: false
